# Upstreamブランチからコンフリクトマーカーをつけたままマージしてプルリクエストを作成

name: Create branch, Merge upstream, Pull request

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  BRANCH: auto_merge
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - run: |
          git checkout -b "$BRANCH"
          git fetch upstream
          git merge upstream/main
          git commit -am "conflict marker"
          git push origin "$BRANCH"
          gh pr create -B "main" -t "Auto merge" -b ""
