# Upstreamブランチからコンフリクトマーカーをつけたままマージしてプルリクエストを作成

name: Create branch, Merge upstream, Pull request

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  BRANCH: auto_merge
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UPSTREAM: https://github.com/snowatfeet/test_for_actions.git
  USER_EMAIL: 39191601+hzuika@users.noreply.github.com
  USER_NAME: hzuika
  
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
      - run: |
          git checkout -b "$BRANCH"
      - run: |
          git remote add upstream ${UPSTREAM}
      - run: |
          git fetch upstream
      - continue-on-error: true
        run: |
          git merge --allow-unrelated-histories upstream/main
          git status
          #git commit -am "confict marker"
      - run: |
          git show
          #git commit -am "conflict marker"
          #git push origin "$BRANCH"
          #gh pr create -B "main" -t "Auto merge" -b ""
