# Upstreamブランチからコンフリクトマーカーをつけたままマージしてプルリクエストを作成

name: Create branch, Merge upstream, Pull request

on:
  # Actions タブから手動でこのワークフローを実行することを許可する
  workflow_dispatch:
  
env:
  BRANCH_PREFIX: auto_merge_
  UPSTREAM: https://github.com/snowatfeet/test_for_actions.git
  REPO: hzuika/test_for_actions_fork
  USER_EMAIL: 39191601+hzuika@users.noreply.github.com
  USER_NAME: hzuika
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    
      # checkoutしないと，ワークフロー時の環境にこのリポジトリが存在しないことになる
      
      - uses: actions/checkout@v3
      
      # (マージ)コミットするときに必要なgit configの情報
      
      - name: Set git config for merge commit
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
          
      - name: Get current time as env var
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "CURRENT_TIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          CURRENT_TIME=$(date +'%Y%m%d_%H%M%S')
          
      - name: Create branch name as env var
        run: |
          T="${{ env.CURRENT_TIME }}"
          YEAR="${T:0:4}"
          MONTH="${T:4:2}"
          DAY="${T:6:2}"
          HOUR="${T:8:2}"
          MIN="${T:10:2}"
          SEC="${T:12:2}"
          BRANCH_SUFFIX="${YEAR}_${MONTH}_${DAY}_${HOUR}_${MIN}_${SEC}"
          BRANCH_NAME="${BRANCH_PREFIX}${{ env.CURRENT_TIME }}"
          echo "BRANCH=${BRANCH_NAME}" >> $GITHUB_ENV
          
      - name: Create and Checkout new branch
        run: git checkout -b "${{ env.BRANCH }}"
          
      - name: Set upstream repo
        run: git remote add upstream ${UPSTREAM}
          
      # デフォルトでfetch-depthが1(shallow clone)なので，mergeするときに，fatal: refusing to merge unrelated historiesが出るのを避ける
      
      - name: Fetch upstream repo
        run: git fetch upstream --unshallow
          
      # upstreamをmergeするが，コンフリクト(エラー)が出てもワークフローを終了させない．
      # マージしたときの出力(コンフリクトのエラーメッセージを変数に格納する
      #echo "::set-output name=MERGE_OUTPUT::$(git merge upstream/main)" だと，
      #改行以降が入らず，文字はエスケープしないといけない
      #複数行の文字列を格納するために環境変数を使う．
      
      - name: Merge upstream repo
        id: merge
        continue-on-error: true
        run: git merge upstream/main >> merge_output.txt
      
      - name: Show merge output
        run: cat merge_output.txt

      - name: Set merge output to env
        run: echo 'MERGE_OUTPUT=$(cat merge_output.txt)' >> $GITHUB_ENV
          
      - name: Commit merge
        run: git commit -am "Merge from upstream"
          
      - name: Push this branch to origin
        run: git push origin "$BRANCH"
          
      # upstream を設定すると，プルリクエストの対象がデフォルトでupstreamになるため，`--repo`で明示的に指定する．
      # gh コマンドでプルリクエストを作成するためには，GH_TOKENが必要
      # マージしたときの出力をプルリクエストの本文に使う
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          T="${{ env.CURRENT_TIME }}"
          YEAR="${T:0:4}"
          MONTH="${T:4:2}"
          DAY="${T:6:2}"
          HOUR="${T:8:2}"
          MIN="${T:10:2}"
          SEC="${T:12:2}"
          TIME="${YEAR}/${MONTH}/${DAY} ${HOUR}:${MIN}:${SEC}"
          gh pr create --head ${{ env.BRANCH }} --base "main" --repo "$REPO" --title "Auto merge (${TIME})" --body "${{ env.MERGE_OUTPUT }}"
