# Upstreamブランチからコンフリクトマーカーをつけたままマージしてプルリクエストを作成

name: Merge upstream, Create pull request

on:
  # Actions タブから手動でこのワークフローを実行することを許可する．
  workflow_dispatch:
  
env:
  BRANCH_PREFIX: auto_merge_
  UPSTREAM_URL: https://github.com/snowatfeet/test_for_actions.git
  USER_EMAIL: 39191601+hzuika@users.noreply.github.com
  USER_NAME: hzuika
  
jobs:
  auto_merge:

    runs-on: ubuntu-latest
    
    steps:
    
      # checkoutしないと，ワークフロー時の環境にこのリポジトリが存在しないことになる．      
      - uses: actions/checkout@v3
      
      - run: echo $GITHUB_CONTEXT
      
      - run: echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/"
      
      - run: ls
      
      - run: git status
      
      # (マージ)コミットするときに必要なgit configを設定する．      
      - name: Set git config for merge commit
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
      
      # 現在時刻を環境変数に格納する．
      # フォーマットは %Y%m%d%H%M%S (例: 20220529032610)
      # 使うときは部分文字列にして使う．
      - name: Get current time as env var
        env:
          TZ: 'Asia/Tokyo'
        run: |
          T=$(date +'%Y%m%d%H%M%S')
          echo "CURRENT_TIME=${T}" >> $GITHUB_ENV
          echo "YEAR=${T:0:4}" >> $GITHUB_ENV
          echo "MONTH=${T:4:2}" >> $GITHUB_ENV
          echo "DAY=${T:6:2}" >> $GITHUB_ENV
          echo "HOUR=${T:8:2}" >> $GITHUB_ENV
          echo "MIN=${T:10:2}" >> $GITHUB_ENV
          echo "SEC=${T:12:2}" >> $GITHUB_ENV
          
      - name: Show current time
        run: echo "${YEAR}/${MONTH}/${DAY} ${HOUR}:${MIN}:${SEC}"
          
      # ブランチ名は別のrunでも使用するので環境変数に入れる．
      - name: Create branch name as env var
        run: |
          BRANCH_SUFFIX="${YEAR}_${MONTH}_${DAY}_${HOUR}_${MIN}_${SEC}"
          BRANCH_NAME="${BRANCH_PREFIX}${BRANCH_SUFFIX}"
          echo "BRANCH=${BRANCH_NAME}" >> $GITHUB_ENV
          
      # 先ほどの環境変数を使用してブランチを作成してチェックアウトする．
      - name: Create and Checkout new branch
        run: git checkout -b ${{ env.BRANCH }}
        
      - run: git status
       
      # エイリアス upstream にupstreamリポジトリのURLを設定する．
      - name: Set upstream repo
        run: git remote add upstream ${UPSTREAM_URL}
        
      - run: git remote -v
          
      # デフォルトでfetch-depthが1(shallow clone)らしく，マージするときに，
      # fatal: refusing to merge unrelated historiesが出るのを避けるために
      # --unshallow オプションをつけてフェッチする．      
      - name: Fetch upstream repo
        run: git fetch upstream --unshallow
      
      # upstreamをマージする．
      # github-scriptsを使って，終了コード，標準出力，標準エラー出力を変数に格納する．
      - name: Merge upstream
        uses: actions/github-script@v6
        with:
          script: |
            const command = 'git merge upstream/main'
            const result = await exec.getExecOutput(command, [], {
              ignoreReturnCode: true,
            })
            console.log(result)
            core.setOutput('EXIT_CODE', result.exitCode)
            core.setOutput('STDOUT', result.stdout)
            core.setOutput('STDERR', result.stderr)
        id: merge
      
      - name: Show merge output
        run: |
          echo "Exit code: ${{ steps.merge.outputs.EXIT_CODE }}"
          echo "stdout:"
          echo "${{ steps.merge.outputs.STDOUT }}"
          echo "stderr:"
          echo "${{ steps.merge.outputs.STDERR }}"

      - run: git ls-files -u
      
      - run: git ls-files -u  | cut -f 1
      
      - run: git ls-files -u  | cut -f 2
      
      - run: git ls-files -u  | cut -f 2 | sort

      # マージしたときにコンフリクトのあるファイルはコミットされない
      # コミットされていないファイル一覧から，ファイル名をカットして，重複を削除して並び替え
      - name: Show conflict files
        run: git ls-files -u  | cut -f 2 | sort -u

      # 終了コードによって，標準出力か，標準エラー出力のどちらかを環境変数に格納する．
      # 一度テキストファイルに格納してから，環境変数に格納する．
      # テキストファイルはGitの対象にならないように親ディテクトリに保存する．
      # echo 'MERGE_OUTPUT=${{ steps.merge.outputs.STDOUT }}' >> $GITHUB_ENV だとエラーになる．
      # シングルクォーテーションをダブルクォーテーションに変えてもエラー
      
      # sed だと標準出力するだけ
      # sed -i がないと上書き保存されない
      - name: Set merge output as env var
        env:
          FILENAME: ../merge_output.txt
        run: |          
          git ls-files -u  | cut -f 2 | sort -u > ../merge_output.txt
      - run: |
          URL_PREFIX=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/${BRANCH}/
          
          sed "s@^@- $URL_PREFIX@g" ../merge_output.txt
          sed -r "s/(.*)/- [\1](\1)/g" ../merge_output.txt
          sed -r "s@(.*)@- [\1](\1)@g" ../merge_output.txt
          sed "s@\(.*\)@- [\1]($URL_PREFIX\1)@g" ../merge_output.txt

          # - [ファイル名](URL/ファイル名) に変換
          sed -i "s@\(.*\)@- [\1]($URL_PREFIX\1)@g" ../merge_output.txt
          # 先頭行に # Conflict files を挿入
          sed -i '1i# Conflict files' ../merge_output.txt
          echo 'MERGE_OUTPUT=$(cat ../merge_output.txt)' >> $GITHUB_ENV
      
      # マージ出力結果を表示する．
      - name: Show merge output
        run: echo ${{ env.MERGE_OUTPUT }}
      
      - name: Git status
        run: git status
        
      - run: git show
      
      # コンフリクトマーカーごとコミットする．          
      - name: Commit merge with conflict marker
        if: ${{ steps.merge.outputs.EXIT_CODE != 0 }}
        run: git commit -am "Merge upstream with conflict marker"
      
      # リモートリポジトリにプッシュして，プルリクエストを作成する．
      
      # マージ出力が Already up to date. であれば実行しない．

      # upstream を設定すると，プルリクエストのマージ先がデフォルトでupstreamになるため，
      # --repo オプションで明示的にリポジトリを指定する．
      # gh コマンドでプルリクエストを作成するためには，GH_TOKENが必要になる．
      # 環境変数に格納したマージ出力結果をプルリクエストの本文に使う．      
      - name: Push and Create pull request
        if: startsWith(steps.merge.outputs.STDOUT, 'Already up to date.') == false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |          
          git push origin "$BRANCH"

          PR_BODY="${{ env.MERGE_OUTPUT }}"
          TIME="${YEAR}/${MONTH}/${DAY} ${HOUR}:${MIN}:${SEC}"
          PR_TITLE="Auto merge upstream (${TIME})"
          gh pr create --head ${{ env.BRANCH }} --base "main" --repo "$GITHUB_REPOSITORY" --title "${PR_TITLE}" --body "${PR_BODY}"
