# Upstreamブランチからコンフリクトマーカーをつけたままマージしてプルリクエストを作成

name: Variable Check

on:
  # Actions タブから手動でこのワークフローを実行することを許可する．
  workflow_dispatch:
  
env:
  P_ENV: auto_merge_
  
jobs:
  var_check:

    runs-on: ubuntu-latest
    
    steps:
    
      - run: |
         echo $P_ENV
         echo "$P_ENV"
         
      - run: |
         echo "A_ENV=Hello" >> $GITHUB_ENV
         echo "$A_ENV"
         
      - run: |
         echo "$A_ENV"
         
      - run: |   
         echo "B_ENV=0" >> $GITHUB_ENV
         echo "$B_ENV"
         echo `$B_ENV`
         echo '$B_ENV'
         echo "${B_ENV}"
         
      - run: |
         C_LOCAL=0
         echo "$C_LOCAL"
         
         echo "C_ENV=$(echo $C_LOCAL)$" >> $GITHUB_ENV
         echo "$C_ENV"
         echo '$C_ENV'
         echo `$C_ENV`
         echo ${C_ENV}

      - env:
          D_LOCAL: $A_ENV
        run: |
          echo $D_LOCAL
